### ISSUE TITLE
Mnemonics for `reduce` and/or `inject`

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-array-methods#1]
In ruby, `inject` can be remembered because the operator (or block) is "injected" between items in the enumerable.

In JavaScript, we can remember `reduce` since it takes a set of many items and "reduces" them to a *single* value. For example:

```
var sum = function sum (a, b) {
  return a + b;
};

[1,2,3].reduce(sum,0) //=> 6
```

**Comment by laurenfazah** [comment]
This language is incorporated into the `reduce` section of the readme @jrhorn424 if you'd like to close

**Comment by jrhorn424** [comment]
Thanks @laurenfazah!
