### ISSUE TITLE
Linter not yelling at us

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/js-array-methods#11]
Expecting "callback defined, but never used" or something along those lines during our code along...
It ain't.

```js
let map = function(array, callback){
  let result = {};
  for (let i = 0, max = array.length; i < max; i++){
    result.push("12");
  }
  return result;
};
```

**Comment by gaand** [comment]
I believe #12 may correct this omission.

**Comment by laurenfazah** [comment]
Fixed, should be good to close @payne-chris-r
