### ISSUE TITLE
Needs solution

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-array-methods#3]

**Comment by laurenfazah** [comment]
Uploaded solutions director on solution branch @gaand @jrhorn424 if you'd like to close

**Comment by gaand** [comment]
@laurenfazah Solutions should go in the training files, e,g, `./lib/*.js` with tests (if possible) in `spec/*.spec.js`.  If you don't have time to get to it, just leave this issue open.  Thanks.

**Comment by jrhorn424** [comment]
Just a note, solution branch is still empty.

**Comment by jrhorn424** [comment]
Available as both `solution` and `demo`.

**Comment by jrhorn424** [comment]
@laurenfazah I'm going to archive the current solution branch since all solutions on that branch are in a different folder. The solution branch I've pushed follows our convention. We can revert this if you want to discuss.
