### ISSUE TITLE
typo in for-each.js

### ISSUE THREAD

**Issue by J-Weeks** [ga-wdi-boston/js-array-methods#5]
const forEach = require('../lib/for-=each.js');

should be:

const forEach = require('../lib/for-each.js');

**Comment by jrhorn424** [comment]
@J-Weeks Mind doing a pull request for @gaand? Thanks.

**Comment by gaand** [comment]
@jrhorn424 Something I'll address on next iteration.  @J-Weeks not that I'm opposed to you correcting and opening a pull request :-).

**Comment by laurenfazah** [comment]
fixed - will be in upcoming push @gaand @J-Weeks
