### ISSUE TITLE
reduce function doesn't take array

### ISSUE THREAD

**Issue by J-Weeks** [ga-wdi-boston/js-array-methods#6]
self explanatory.

**Comment by jrhorn424** [comment]
Line number and file?

**Comment by jrhorn424** [comment]
I think you might have missed the fact that developers write their own versions of some array methods. We don't want them overriding Array.prototype, so they have to pass arrays they want to mutate.

> We'll explore and implement proxies for a variety of the JavaScript Array methods.

**Comment by laurenfazah** [comment]
Should this be an open issue? @J-Weeks @jrhorn424

**Comment by gaand** [comment]
@laurenfazah I think not.  But @J-Weeks should confirm

**Comment by jrhorn424** [comment]
I believe this is a duplicate of #9

**Comment by gaand** [comment]
I think it might have been the mirror of a duplicate. :-P.
