### ISSUE TITLE
Use ruby-enumerable javascript array creator for labs at the end

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-array-methods#8]
See repo [An Introduction to Ruby Enumerables](/ga-wdi-boston/ruby-enumerable)

**Comment by jrhorn424** [comment]
Broken link :(

**Comment by jrhorn424** [comment]
This? https://github.com/ga-wdi-boston/ruby-enumerable

**Comment by gaand** [comment]
Fixed it, I believe.  Missing leading `/`.

**Comment by jrhorn424** [comment]
Ah, right! The array creator! That was slick. I like it.

**Comment by jrhorn424** [comment]
... and I forgot it. Filename?

**Comment by gaand** [comment]
@jrhorn424 

Repo should be [Ruby Array Methods (versus JavaScript)](/ga-wdi-boston/ruby-vs-js-array-methods)

in `lib/`, `people.js` and `person.js`, `cities.js` and `city.js`.

**Comment by gaand** [comment]
I'm wondering if this is too much at this point.
