### ISSUE TITLE
reduce proxy missing array argument.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-array-methods#9]
in js-array-methods/lib/reduce.js

**Comment by jrhorn424** [comment]
Is this resolved? It appears fixed.

**Comment by gaand** [comment]
Your solution includes array, callback, and initial value.  The boiler plate does not, so not closed yet.

**Comment by laurenfazah** [comment]
Fixed, should be good to close @gaand @jrhorn424
